name: Actualizar versión.json

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Crear carpeta bin si no existe
      run: |
        if (!(Test-Path bin)) {
          mkdir bin
        }
       
    - name: Copiar version.json a updates
      run: |
        if (!(Test-Path updates)) {
          mkdir updates
        }
        copy version.json updates\

    - name: Commit y push a updates
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add updates/
        git commit -m "Actualizo version.json"
        git push
